In [30]:
import pandas as pd

In [31]:
df = pd.read_csv("nome_alunos.csv", sep=";")

In [32]:
df

,nome,ID_aluno,dominio,email
0,JOSE,189,@dominiodoemail.com.br,jose@dominiodoemail.com.br
1,JOAO,58,@servicodoemail.com,joao@servicodoemail.com
2,ANTONIO,204,@servicodoemail.com,antonio@servicodoemail.com
3,FRANCISCO,383,@dominiodoemail.com.br,francisco@dominiodoemail.com.br
4,CARLOS,231,@servicodoemail.com,carlos@servicodoemail.com
...,...,...,...,...
395,ROSANE,9,@dominiodoemail.com.br,rosane@dominiodoemail.com.br
396,IVONETE,378,@servicodoemail.com,ivonete@servicodoemail.com
397,LUCIANE,50,@dominiodoemail.com.br,luciane@dominiodoemail.com.br
398,ISADORA,244,@dominiodoemail.com.br,isadora@dominiodoemail.com.br
399,NILZA,387,@servicodoemail.com,nilza@servicodoemail.com

# Iterando sobre o dataframe

In [33]:
for i in df:
    print(i)

nome
ID_aluno
dominio
email

In [34]:
#Retorna todos os dados da linha
for i, row in df.iterrows():
    print(f"Linha: {i}")
    print("")
    print(row)
    print("")

Linha: 0

nome                              JOSE
ID_aluno                           189
dominio         @dominiodoemail.com.br
email       jose@dominiodoemail.com.br
Name: 0, dtype: object

Linha: 1

nome                           JOAO
ID_aluno                         58
dominio         @servicodoemail.com
email       joao@servicodoemail.com
Name: 1, dtype: object

Linha: 2

nome                           ANTONIO
ID_aluno                           204
dominio            @servicodoemail.com
email       antonio@servicodoemail.com
Name: 2, dtype: object

Linha: 3

nome                              FRANCISCO
ID_aluno                                383
dominio              @dominiodoemail.com.br
email       francisco@dominiodoemail.com.br
Name: 3, dtype: object

Linha: 4

nome                           CARLOS
ID_aluno                          231
dominio           @servicodoemail.com
email       carlos@servicodoemail.com
Name: 4, dtype: object

Linha: 5

nome                           PAULO
ID_aluno                         285
dominio          @servicodoemail.com
email       paulo@servicodoemail.com
Name: 5, dtype: object

Linha: 6

nome                              PEDRO
ID_aluno                            105
dominio          @dominiodoemail.com.br
email       pedro@dominiodoemail.com.br
Name: 6, dtype: object

Linha: 7

nome                           LUCAS
ID_aluno                         237
dominio          @servicodoemail.com
email       lucas@servicodoemail.com
Name: 7, dtype: object

Linha: 8

nome                           LUIZ
ID_aluno                          5
dominio         @servicodoemail.com
email       luiz@servicodoemail.com
Name: 8, dtype: object

Linha: 9

nome                              MARCOS
ID_aluno                             268
dominio           @dominiodoemail.com.br
email       marcos@dominiodoemail.com.br
Name: 9, dtype: object

Linha: 10

nome                              LUIS
ID_aluno                            59
dominio         @dominiodoemail.com.br
email       luis@dominiodoemail.com.br
Name: 10, dtype: object

Linha: 11

nome                              GABRIEL
ID_aluno                              132
dominio            @dominiodoemail.com.br
email       gabriel@dominiodoemail.com.br
Name: 11, dtype: object

Linha: 12

nome                           RAFAEL
ID_aluno                           13
dominio           @servicodoemail.com
email       rafael@servicodoemail.com
Name: 12, dtype: object

Linha: 13

nome                           DANIEL
ID_aluno                          172
dominio           @servicodoemail.com
email       daniel@servicodoemail.com
Name: 13, dtype: object

Linha: 14

nome                           MARCELO
ID_aluno                           322
dominio            @servicodoemail.com
email       marcelo@servicodoemail.com
Name: 14, dtype: object

Linha: 15

nome                              BRUNO
ID_aluno                             90
dominio          @dominiodoemail.com.br
email       bruno@dominiodoemail.com.br
Name: 15, dtype: object

Linha: 16

nome                           EDUARDO
ID_aluno                           250
dominio            @servicodoemail.com
email       eduardo@servicodoemail.com
Name: 16, dtype: object

Linha: 17

nome                              FELIPE
ID_aluno                             171
dominio           @dominiodoemail.com.br
email       felipe@dominiodoemail.com.br
Name: 17, dtype: object

Linha: 18

nome                              RAIMUNDO
ID_aluno                               169
dominio             @dominiodoemail.com.br
email       raimundo@dominiodoemail.com.br
Name: 18, dtype: object

Linha: 19

nome                           RODRIGO
ID_aluno                           150
dominio            @servicodoemail.com
email       rodrigo@servicodoemail.com
Name: 19, dtype: object

Linha: 20

nome                              MANOEL
ID_aluno                             225
dominio           @dominiodoemail.com.br
email       manoel@dominiodoemail.com.br
Name: 20, dtype: object

Linha: 21

nome                           MATEUS
ID_aluno                           92
dominio           @servicodoemail.com
email       mateus@servicodoemail.com
Name: 21, dtype: object

Linha: 22

nome                           ANDRE
ID_aluno                         212
dominio          @servicodoemail.com
email       andre@servicodoemail.com
Name: 22, dtype: object

Linha: 23

nome                           FERNANDO
ID_aluno                            219
dominio             @servicodoemail.com
email       fernando@servicodoemail.com
Name: 23, dtype: object

Linha: 24

nome                           FABIO
ID_aluno                         109
dominio          @servicodoemail.com
email       fabio@servicodoemail.com
Name: 24, dtype: object

Linha: 25

nome                              LEONARDO
ID_aluno                               381
dominio             @dominiodoemail.com.br
email       leonardo@dominiodoemail.com.br
Name: 25, dtype: object

Linha: 26

nome                              GUSTAVO
ID_aluno                              173
dominio            @dominiodoemail.com.br
email       gustavo@dominiodoemail.com.br
Name: 26, dtype: object

Linha: 27

nome                           GUILHERME
ID_aluno                             186
dominio              @servicodoemail.com
email       guilherme@servicodoemail.com
Name: 27, dtype: object

Linha: 28

nome                              LEANDRO
ID_aluno                              139
dominio            @dominiodoemail.com.br
email       leandro@dominiodoemail.com.br
Name: 28, dtype: object

Linha: 29

nome                           TIAGO
ID_aluno                         315
dominio          @servicodoemail.com
email       tiago@servicodoemail.com
Name: 29, dtype: object

Linha: 30

nome                           ANDERSON
ID_aluno                            264
dominio             @servicodoemail.com
email       anderson@servicodoemail.com
Name: 30, dtype: object

Linha: 31

nome                           RICARDO
ID_aluno                           358
dominio            @servicodoemail.com
email       ricardo@servicodoemail.com
Name: 31, dtype: object

Linha: 32

nome                           MARCIO
ID_aluno                          286
dominio           @servicodoemail.com
email       marcio@servicodoemail.com
Name: 32, dtype: object

Linha: 33

nome                              JORGE
ID_aluno                            129
dominio          @dominiodoemail.com.br
email       jorge@dominiodoemail.com.br
Name: 33, dtype: object

Linha: 34

nome                              SEBASTIAO
ID_aluno                                 76
dominio              @dominiodoemail.com.br
email       sebastiao@dominiodoemail.com.br
Name: 34, dtype: object

Linha: 35

nome                              ALEXANDRE
ID_aluno                                126
dominio              @dominiodoemail.com.br
email       alexandre@dominiodoemail.com.br
Name: 35, dtype: object

Linha: 36

nome                              ROBERTO
ID_aluno                               53
dominio            @dominiodoemail.com.br
email       roberto@dominiodoemail.com.br
Name: 36, dtype: object

Linha: 37

nome                              EDSON
ID_aluno                             93
dominio          @dominiodoemail.com.br
email       edson@dominiodoemail.com.br
Name: 37, dtype: object

Linha: 38

nome                           DIEGO
ID_aluno                         297
dominio          @servicodoemail.com
email       diego@servicodoemail.com
Name: 38, dtype: object

Linha: 39

nome                              VITOR
ID_aluno                             79
dominio          @dominiodoemail.com.br
email       vitor@dominiodoemail.com.br
Name: 39, dtype: object

Linha: 40

nome                           SERGIO
ID_aluno                           37
dominio           @servicodoemail.com
email       sergio@servicodoemail.com
Name: 40, dtype: object

Linha: 41

nome                           CLAUDIO
ID_aluno                           227
dominio            @servicodoemail.com
email       claudio@servicodoemail.com
Name: 41, dtype: object

Linha: 42

nome                           MATHEUS
ID_aluno                           228
dominio            @servicodoemail.com
email       matheus@servicodoemail.com
Name: 42, dtype: object

Linha: 43

nome                           THIAGO
ID_aluno                           49
dominio           @servicodoemail.com
email       thiago@servicodoemail.com
Name: 43, dtype: object

Linha: 44

nome                           GERALDO
ID_aluno                           280
dominio            @servicodoemail.com
email       geraldo@servicodoemail.com
Name: 44, dtype: object

Linha: 45

nome                              ADRIANO
ID_aluno                               91
dominio            @dominiodoemail.com.br
email       adriano@dominiodoemail.com.br
Name: 45, dtype: object

Linha: 46

nome                           LUCIANO
ID_aluno                           373
dominio            @servicodoemail.com
email       luciano@servicodoemail.com
Name: 46, dtype: object

Linha: 47

nome                              JULIO
ID_aluno                             56
dominio          @dominiodoemail.com.br
email       julio@dominiodoemail.com.br
Name: 47, dtype: object

Linha: 48

nome                              RENATO
ID_aluno                             223
dominio           @dominiodoemail.com.br
email       renato@dominiodoemail.com.br
Name: 48, dtype: object

Linha: 49

nome                           ALEX
ID_aluno                        222
dominio         @servicodoemail.com
email       alex@servicodoemail.com
Name: 49, dtype: object

Linha: 50

nome                              VINICIUS
ID_aluno                               303
dominio             @dominiodoemail.com.br
email       vinicius@dominiodoemail.com.br
Name: 50, dtype: object

Linha: 51

nome                              ROGERIO
ID_aluno                              343
dominio            @dominiodoemail.com.br
email       rogerio@dominiodoemail.com.br
Name: 51, dtype: object

Linha: 52

nome                           SAMUEL
ID_aluno                          375
dominio           @servicodoemail.com
email       samuel@servicodoemail.com
Name: 52, dtype: object

Linha: 53

nome                           RONALDO
ID_aluno                            66
dominio            @servicodoemail.com
email       ronaldo@servicodoemail.com
Name: 53, dtype: object

Linha: 54

nome                              MARIO
ID_aluno                            145
dominio          @dominiodoemail.com.br
email       mario@dominiodoemail.com.br
Name: 54, dtype: object

Linha: 55

nome                              FLAVIO
ID_aluno                             305
dominio           @dominiodoemail.com.br
email       flavio@dominiodoemail.com.br
Name: 55, dtype: object

Linha: 56

nome                              DOUGLAS
ID_aluno                              266
dominio            @dominiodoemail.com.br
email       douglas@dominiodoemail.com.br
Name: 56, dtype: object

Linha: 57

nome                           IGOR
ID_aluno                        178
dominio         @servicodoemail.com
email       igor@servicodoemail.com
Name: 57, dtype: object

Linha: 58

nome                           DAVI
ID_aluno                        174
dominio         @servicodoemail.com
email       davi@servicodoemail.com
Name: 58, dtype: object

Linha: 59

nome                              MANUEL
ID_aluno                             261
dominio           @dominiodoemail.com.br
email       manuel@dominiodoemail.com.br
Name: 59, dtype: object

Linha: 60

nome                              JEFERSON
ID_aluno                               366
dominio             @dominiodoemail.com.br
email       jeferson@dominiodoemail.com.br
Name: 60, dtype: object

Linha: 61

nome                           CICERO
ID_aluno                          107
dominio           @servicodoemail.com
email       cicero@servicodoemail.com
Name: 61, dtype: object

Linha: 62

nome                           VICTOR
ID_aluno                          187
dominio           @servicodoemail.com
email       victor@servicodoemail.com
Name: 62, dtype: object

Linha: 63

nome                           MIGUEL
ID_aluno                          278
dominio           @servicodoemail.com
email       miguel@servicodoemail.com
Name: 63, dtype: object

Linha: 64

nome                           ROBSON
ID_aluno                           63
dominio           @servicodoemail.com
email       robson@servicodoemail.com
Name: 64, dtype: object

Linha: 65

nome                              MAURICIO
ID_aluno                               349
dominio             @dominiodoemail.com.br
email       mauricio@dominiodoemail.com.br
Name: 65, dtype: object

Linha: 66

nome                           DANILO
ID_aluno                            6
dominio           @servicodoemail.com
email       danilo@servicodoemail.com
Name: 66, dtype: object

Linha: 67

nome                              HENRIQUE
ID_aluno                               272
dominio             @dominiodoemail.com.br
email       henrique@dominiodoemail.com.br
Name: 67, dtype: object

Linha: 68

nome                           CAIO
ID_aluno                        210
dominio         @servicodoemail.com
email       caio@servicodoemail.com
Name: 68, dtype: object

Linha: 69

nome                           REGINALDO
ID_aluno                             207
dominio              @servicodoemail.com
email       reginaldo@servicodoemail.com
Name: 69, dtype: object

Linha: 70

nome                              JOAQUIM
ID_aluno                              194
dominio            @dominiodoemail.com.br
email       joaquim@dominiodoemail.com.br
Name: 70, dtype: object

Linha: 71

nome                           BENEDITO
ID_aluno                            326
dominio             @servicodoemail.com
email       benedito@servicodoemail.com
Name: 71, dtype: object

Linha: 72

nome                           GILBERTO
ID_aluno                             17
dominio             @servicodoemail.com
email       gilberto@servicodoemail.com
Name: 72, dtype: object

Linha: 73

nome                           MARCO
ID_aluno                         230
dominio          @servicodoemail.com
email       marco@servicodoemail.com
Name: 73, dtype: object

Linha: 74

nome                           ALAN
ID_aluno                         36
dominio         @servicodoemail.com
email       alan@servicodoemail.com
Name: 74, dtype: object

Linha: 75

nome                              NELSON
ID_aluno                             136
dominio           @dominiodoemail.com.br
email       nelson@dominiodoemail.com.br
Name: 75, dtype: object

Linha: 76

nome                              CRISTIANO
ID_aluno                                369
dominio              @dominiodoemail.com.br
email       cristiano@dominiodoemail.com.br
Name: 76, dtype: object

Linha: 77

nome                           ELIAS
ID_aluno                          42
dominio          @servicodoemail.com
email       elias@servicodoemail.com
Name: 77, dtype: object

Linha: 78

nome                           WILSON
ID_aluno                           57
dominio           @servicodoemail.com
email       wilson@servicodoemail.com
Name: 78, dtype: object

Linha: 79

nome                              VALDIR
ID_aluno                             131
dominio           @dominiodoemail.com.br
email       valdir@dominiodoemail.com.br
Name: 79, dtype: object

Linha: 80

nome                              EMERSON
ID_aluno                              163
dominio            @dominiodoemail.com.br
email       emerson@dominiodoemail.com.br
Name: 80, dtype: object

Linha: 81

nome                              LUAN
ID_aluno                           101
dominio         @dominiodoemail.com.br
email       luan@dominiodoemail.com.br
Name: 81, dtype: object

Linha: 82

nome                              DAVID
ID_aluno                            118
dominio          @dominiodoemail.com.br
email       david@dominiodoemail.com.br
Name: 82, dtype: object

Linha: 83

nome                              RENAN
ID_aluno                            140
dominio          @dominiodoemail.com.br
email       renan@dominiodoemail.com.br
Name: 83, dtype: object

Linha: 84

nome                           SEVERINO
ID_aluno                            216
dominio             @servicodoemail.com
email       severino@servicodoemail.com
Name: 84, dtype: object

Linha: 85

nome                              FABRICIO
ID_aluno                               220
dominio             @dominiodoemail.com.br
email       fabricio@dominiodoemail.com.br
Name: 85, dtype: object

Linha: 86

nome                              MAURO
ID_aluno                            338
dominio          @dominiodoemail.com.br
email       mauro@dominiodoemail.com.br
Name: 86, dtype: object

Linha: 87

nome                           JONAS
ID_aluno                         274
dominio          @servicodoemail.com
email       jonas@servicodoemail.com
Name: 87, dtype: object

Linha: 88

nome                           GILMAR
ID_aluno                          165
dominio           @servicodoemail.com
email       gilmar@servicodoemail.com
Name: 88, dtype: object

Linha: 89

nome                           JEAN
ID_aluno                         75
dominio         @servicodoemail.com
email       jean@servicodoemail.com
Name: 89, dtype: object

Linha: 90

nome                           FABIANO
ID_aluno                           195
dominio            @servicodoemail.com
email       fabiano@servicodoemail.com
Name: 90, dtype: object

Linha: 91

nome                              WESLEY
ID_aluno                             238
dominio           @dominiodoemail.com.br
email       wesley@dominiodoemail.com.br
Name: 91, dtype: object

Linha: 92

nome                              DIOGO
ID_aluno                            346
dominio          @dominiodoemail.com.br
email       diogo@dominiodoemail.com.br
Name: 92, dtype: object

Linha: 93

nome                           ADILSON
ID_aluno                           301
dominio            @servicodoemail.com
email       adilson@servicodoemail.com
Name: 93, dtype: object

Linha: 94

nome                              JAIR
ID_aluno                           217
dominio         @dominiodoemail.com.br
email       jair@dominiodoemail.com.br
Name: 94, dtype: object

Linha: 95

nome                              ALESSANDRO
ID_aluno                                 190
dominio               @dominiodoemail.com.br
email       alessandro@dominiodoemail.com.br
Name: 95, dtype: object

Linha: 96

nome                           EVERTON
ID_aluno                           233
dominio            @servicodoemail.com
email       everton@servicodoemail.com
Name: 96, dtype: object

Linha: 97

nome                           OSVALDO
ID_aluno                            71
dominio            @servicodoemail.com
email       osvaldo@servicodoemail.com
Name: 97, dtype: object

Linha: 98

nome                           GILSON
ID_aluno                           12
dominio           @servicodoemail.com
email       gilson@servicodoemail.com
Name: 98, dtype: object

Linha: 99

nome                           WILLIAN
ID_aluno                           253
dominio            @servicodoemail.com
email       willian@servicodoemail.com
Name: 99, dtype: object

Linha: 100

nome                              JOEL
ID_aluno                           361
dominio         @dominiodoemail.com.br
email       joel@dominiodoemail.com.br
Name: 100, dtype: object

Linha: 101

nome                           SILVIO
ID_aluno                          282
dominio           @servicodoemail.com
email       silvio@servicodoemail.com
Name: 101, dtype: object

Linha: 102

nome                              HELIO
ID_aluno                             68
dominio          @dominiodoemail.com.br
email       helio@dominiodoemail.com.br

Linha: 352

nome                              LARA
ID_aluno                           112
dominio         @dominiodoemail.com.br
email       lara@dominiodoemail.com.br
Name: 352, dtype: object

Linha: 353

nome                              CLEIDE
ID_aluno                             116
dominio           @dominiodoemail.com.br
email       cleide@dominiodoemail.com.br
Name: 353, dtype: object

Linha: 354

nome                           NICOLE
ID_aluno                          310
dominio           @servicodoemail.com
email       nicole@servicodoemail.com
Name: 354, dtype: object

Linha: 355

nome                           CECILIA
ID_aluno                            33
dominio            @servicodoemail.com
email       cecilia@servicodoemail.com
Name: 355, dtype: object

Linha: 356

nome                              YASMIN
ID_aluno                             153
dominio           @dominiodoemail.com.br
email       yasmin@dominiodoemail.com.br
Name: 356, dtype: object

Linha: 357

nome                           CONCEICAO
ID_aluno                             331
dominio              @servicodoemail.com
email       conceicao@servicodoemail.com
Name: 357, dtype: object

Linha: 358

nome                              INGRID
ID_aluno                             397
dominio           @dominiodoemail.com.br
email       ingrid@dominiodoemail.com.br
Name: 358, dtype: object

Linha: 359

nome                           SELMA
ID_aluno                          39
dominio          @servicodoemail.com
email       selma@servicodoemail.com
Name: 359, dtype: object

Linha: 360

nome                              LEILA
ID_aluno                             25
dominio          @dominiodoemail.com.br
email       leila@dominiodoemail.com.br
Name: 360, dtype: object

Linha: 361

nome                           RAIANE
ID_aluno                           30
dominio           @servicodoemail.com
email       raiane@servicodoemail.com
Name: 361, dtype: object

Linha: 362

nome                           ESTER
ID_aluno                         327
dominio          @servicodoemail.com
email       ester@servicodoemail.com
Name: 362, dtype: object

Linha: 363

nome                           REGIANE
ID_aluno                           200
dominio            @servicodoemail.com
email       regiane@servicodoemail.com
Name: 363, dtype: object

Linha: 364

nome                              MARISA
ID_aluno                             206
dominio           @dominiodoemail.com.br
email       marisa@dominiodoemail.com.br
Name: 364, dtype: object

Linha: 365

nome                              EUNICE
ID_aluno                             321
dominio           @dominiodoemail.com.br
email       eunice@dominiodoemail.com.br
Name: 365, dtype: object

Linha: 366

nome                           KELLY
ID_aluno                         372
dominio          @servicodoemail.com
email       kelly@servicodoemail.com
Name: 366, dtype: object

Linha: 367

nome                           TAINARA
ID_aluno                           180
dominio            @servicodoemail.com
email       tainara@servicodoemail.com
Name: 367, dtype: object

Linha: 368

nome                           IARA
ID_aluno                        377
dominio         @servicodoemail.com
email       iara@servicodoemail.com
Name: 368, dtype: object

Linha: 369

nome                           JOELMA
ID_aluno                          260
dominio           @servicodoemail.com
email       joelma@servicodoemail.com
Name: 369, dtype: object

Linha: 370

nome                           MARINALVA
ID_aluno                             181
dominio              @servicodoemail.com
email       marinalva@servicodoemail.com
Name: 370, dtype: object

Linha: 371

nome                              TERESINHA
ID_aluno                                312
dominio              @dominiodoemail.com.br
email       teresinha@dominiodoemail.com.br
Name: 371, dtype: object

Linha: 372

nome                              REBECA
ID_aluno                             259
dominio           @dominiodoemail.com.br
email       rebeca@dominiodoemail.com.br
Name: 372, dtype: object

Linha: 373

nome                              GERALDA
ID_aluno                              209
dominio            @dominiodoemail.com.br
email       geralda@dominiodoemail.com.br
Name: 373, dtype: object

Linha: 374

nome                           CLEONICE
ID_aluno                            265
dominio             @servicodoemail.com
email       cleonice@servicodoemail.com
Name: 374, dtype: object

Linha: 375

nome                              ALEXANDRA
ID_aluno                                127
dominio              @dominiodoemail.com.br
email       alexandra@dominiodoemail.com.br
Name: 375, dtype: object

Linha: 376

nome                           MARA
ID_aluno                        382
dominio         @servicodoemail.com
email       mara@servicodoemail.com
Name: 376, dtype: object

Linha: 377

nome                           JENIFER
ID_aluno                           208
dominio            @servicodoemail.com
email       jenifer@servicodoemail.com
Name: 377, dtype: object

Linha: 378

nome                           ELIZANGELA
ID_aluno                              309
dominio               @servicodoemail.com
email       elizangela@servicodoemail.com
Name: 378, dtype: object

Linha: 379

nome                              LILIANE
ID_aluno                              296
dominio            @dominiodoemail.com.br
email       liliane@dominiodoemail.com.br
Name: 379, dtype: object

Linha: 380

nome                           LIDIA
ID_aluno                          62
dominio          @servicodoemail.com
email       lidia@servicodoemail.com
Name: 380, dtype: object

Linha: 381

nome                           IRACEMA
ID_aluno                           380
dominio            @servicodoemail.com
email       iracema@servicodoemail.com
Name: 381, dtype: object

Linha: 382

nome                           LIDIANE
ID_aluno                           239
dominio            @servicodoemail.com
email       lidiane@servicodoemail.com
Name: 382, dtype: object

Linha: 383

nome                           IRACI
ID_aluno                         283
dominio          @servicodoemail.com
email       iraci@servicodoemail.com
Name: 383, dtype: object

Linha: 384

nome                           MARILIA
ID_aluno                           141
dominio            @servicodoemail.com
email       marilia@servicodoemail.com
Name: 384, dtype: object

Linha: 385

nome                           SHEILA
ID_aluno                          149
dominio           @servicodoemail.com
email       sheila@servicodoemail.com
Name: 385, dtype: object

Linha: 386

nome                           INES
ID_aluno                        379
dominio         @servicodoemail.com
email       ines@servicodoemail.com
Name: 386, dtype: object

Linha: 387

nome                              NAIARA
ID_aluno                              82
dominio           @dominiodoemail.com.br
email       naiara@dominiodoemail.com.br
Name: 387, dtype: object

Linha: 388

nome                           POLIANA
ID_aluno                           391
dominio            @servicodoemail.com
email       poliana@servicodoemail.com
Name: 388, dtype: object

Linha: 389

nome                           DALVA
ID_aluno                         106
dominio          @servicodoemail.com
email       dalva@servicodoemail.com
Name: 389, dtype: object

Linha: 390

nome                           LURDES
ID_aluno                           72
dominio           @servicodoemail.com
email       lurdes@servicodoemail.com
Name: 390, dtype: object

Linha: 391

nome                              TERESA
ID_aluno                             115
dominio           @dominiodoemail.com.br
email       teresa@dominiodoemail.com.br
Name: 391, dtype: object

Linha: 392

nome                           ZILDA
ID_aluno                         235
dominio          @servicodoemail.com
email       zilda@servicodoemail.com
Name: 392, dtype: object

Linha: 393

nome                           LUCILENE
ID_aluno                            348
dominio             @servicodoemail.com
email       lucilene@servicodoemail.com
Name: 393, dtype: object

Linha: 394

nome                              CLARA
ID_aluno                            234
dominio          @dominiodoemail.com.br
email       clara@dominiodoemail.com.br
Name: 394, dtype: object

Linha: 395

nome                              ROSANE
ID_aluno                               9
dominio           @dominiodoemail.com.br
email       rosane@dominiodoemail.com.br
Name: 395, dtype: object

Linha: 396

nome                           IVONETE
ID_aluno                           378
dominio            @servicodoemail.com
email       ivonete@servicodoemail.com
Name: 396, dtype: object

Linha: 397

nome                              LUCIANE
ID_aluno                               50
dominio            @dominiodoemail.com.br
email       luciane@dominiodoemail.com.br
Name: 397, dtype: object

Linha: 398

nome                              ISADORA
ID_aluno                              244
dominio            @dominiodoemail.com.br
email       isadora@dominiodoemail.com.br
Name: 398, dtype: object

Linha: 399

nome                           NILZA
ID_aluno                         387
dominio          @servicodoemail.com
email       nilza@servicodoemail.com
Name: 399, dtype: object

In [35]:
#Retorna todos os dados de uma coluna especÃ­fica
for i in df['nome']:
    print(i)

JOSE
JOAO
ANTONIO
FRANCISCO
CARLOS
PAULO
PEDRO
LUCAS
LUIZ
MARCOS
LUIS
GABRIEL
RAFAEL
DANIEL
MARCELO
BRUNO
EDUARDO
FELIPE
RAIMUNDO
RODRIGO
MANOEL
MATEUS
ANDRE
FERNANDO
FABIO
LEONARDO
GUSTAVO
GUILHERME
LEANDRO
TIAGO
ANDERSON
RICARDO
MARCIO
JORGE
SEBASTIAO
ALEXANDRE
ROBERTO
EDSON
DIEGO
VITOR
SERGIO
CLAUDIO
MATHEUS
THIAGO
GERALDO
ADRIANO
LUCIANO
JULIO
RENATO
ALEX
VINICIUS
ROGERIO
SAMUEL
RONALDO
MARIO
FLAVIO
DOUGLAS
IGOR
DAVI
MANUEL
JEFERSON
CICERO
VICTOR
MIGUEL
ROBSON
MAURICIO
DANILO
HENRIQUE
CAIO
REGINALDO
JOAQUIM
BENEDITO
GILBERTO
MARCO
ALAN
NELSON
CRISTIANO
ELIAS
WILSON
VALDIR
EMERSON
LUAN
DAVID
RENAN
SEVERINO
FABRICIO
MAURO
JONAS
GILMAR
JEAN
FABIANO
WESLEY
DIOGO
ADILSON
JAIR
ALESSANDRO
EVERTON
OSVALDO
GILSON
WILLIAN
JOEL
SILVIO
HELIO
MAICON
REINALDO
PABLO
ARTUR
VAGNER
VALTER
CELSO
IVAN
CLEITON
VANDERLEI
VICENTE
ARTHUR
MILTON
DOMINGOS
WAGNER
SANDRO
MOISES
EDILSON
ADEMIR
ADAO
EVANDRO
CESAR
VALMIR
MURILO
JULIANO
EDVALDO
AILTON
JUNIOR
BRENO
NICOLAS
RUAN
ALBERTO
RUBENS
NILTON
AUGUSTO
CLEBER
OSMAR
NILSON
ORLANDO
HUGO
OTAVIO
VINICIOS
ITALO
WILIAN
ALISSON
APARECIDO
ISRAEL
EDMILSON
JOSUE
GERSON
CAUA
SIDNEI
EMANUEL
VALDEMAR
JAIME
EDIVALDO
ARNALDO
MOACIR
DAMIAO
ISMAEL
NIVALDO
JAIRO
ISAIAS
MICHEL
ANGELO
CRISTIAN
WELLINGTON
ALEXANDRO
VALDEMIR
WANDERSON
JAILSON
DENIS
RIAN
CELIO
CLAUDINEI
DENILSON
IAGO
EDER
YURI
CHARLES
MARLON
ALISON
JONATAN
ERIC
ELTON
VALDECIR
WESLEI
NATANAEL
ERICK
AGNALDO
KAUAN
ODAIR
WALTER
ARLINDO
MICHAEL
ALVARO
GEOVANE
MARIA
ANA
FRANCISCA
ANTONIA
ADRIANA
JULIANA
MARCIA
FERNANDA
PATRICIA
ALINE
SANDRA
CAMILA
AMANDA
BRUNA
JESSICA
LETICIA
JULIA
LUCIANA
VANESSA
MARIANA
GABRIELA
VERA
VITORIA
LARISSA
CLAUDIA
BEATRIZ
RITA
LUANA
SONIA
RENATA
ELIANE
JOSEFA
SIMONE
NATALIA
CRISTIANE
CARLA
DEBORA
ROSANGELA
JAQUELINE
ROSA
APARECIDA
DANIELA
MARLENE
TEREZINHA
RAIMUNDA
ANDREIA
FABIANA
LUCIA
RAQUEL
ANGELA
RAFAELA
JOANA
LUZIA
ELAINE
REGINA
DANIELE
SUELI
DAIANE
ALESSANDRA
ISABEL
SARA
BIANCA
FLAVIA
ERICA
VIVIANE
SILVANA
PRISCILA
PAULA
LUIZA
TEREZA
ISABELA
MARTA
CAROLINE
JANAINA
LAURA
MARLI
TATIANE
MARINA
SILVIA
MONICA
TAIS
MICHELE
SOLANGE
EDNA
FATIMA
HELENA
CRISTINA
ALICE
CAROLINA
ROSANA
ANDRESSA
CELIA
VALERIA
ELIANA
SABRINA
ANDREA
TANIA
BARBARA
THAIS
DENISE
ROSELI
GISELE
MARILENE
KATIA
EVA
MILENA
EDUARDA
ELISANGELA
VILMA
GEOVANA
LUCIENE
TAMIRES
TATIANA
ROBERTA
ELZA
TALITA
MARCELA
PAMELA
VANIA
IRENE
JOSIANE
LIVIA
CINTIA
IVONE
LAIS
BENEDITA
SEBASTIANA
TAINA
JOICE
MIRIAN
ELIZABETE
ANGELICA
GABRIELE
BRENDA
VERONICA
ROSILENE
KARINA
NAIR
NEUSA
MARGARIDA
NEUZA
NEIDE
RAISSA
MAIARA
LORENA
FRANCIELE
SAMARA
LILIAN
JANETE
CICERA
GIOVANA
SEVERINA
LARA
CLEIDE
NICOLE
CECILIA
YASMIN
CONCEICAO
INGRID
SELMA
LEILA
RAIANE
ESTER
REGIANE
MARISA
EUNICE
KELLY
TAINARA
IARA
JOELMA
MARINALVA
TERESINHA
REBECA
GERALDA
CLEONICE
ALEXANDRA
MARA
JENIFER
ELIZANGELA
LILIANE
LIDIA
IRACEMA
LIDIANE
IRACI
MARILIA
SHEILA
INES
NAIARA
POLIANA
DALVA
LURDES
TERESA
ZILDA
LUCILENE
CLARA
ROSANE
IVONETE
LUCIANE
ISADORA
NILZA

In [36]:
#Retornando dados de mais de uma coluna especificada
for linha, idaluno in df[['nome', 'ID_aluno']].iterrows():
    print(idaluno)

nome        JOSE
ID_aluno     189
Name: 0, dtype: object
nome        JOAO
ID_aluno      58
Name: 1, dtype: object
nome        ANTONIO
ID_aluno        204
Name: 2, dtype: object
nome        FRANCISCO
ID_aluno          383
Name: 3, dtype: object
nome        CARLOS
ID_aluno       231
Name: 4, dtype: object
nome        PAULO
ID_aluno      285
Name: 5, dtype: object
nome        PEDRO
ID_aluno      105
Name: 6, dtype: object
nome        LUCAS
ID_aluno      237
Name: 7, dtype: object
nome        LUIZ
ID_aluno       5
Name: 8, dtype: object
nome        MARCOS
ID_aluno       268
Name: 9, dtype: object
nome        LUIS
ID_aluno      59
Name: 10, dtype: object
nome        GABRIEL
ID_aluno        132
Name: 11, dtype: object
nome        RAFAEL
ID_aluno        13
Name: 12, dtype: object
nome        DANIEL
ID_aluno       172
Name: 13, dtype: object
nome        MARCELO
ID_aluno        322
Name: 14, dtype: object
nome        BRUNO
ID_aluno       90
Name: 15, dtype: object
nome        EDUARDO
ID_aluno        250
Name: 16, dtype: object
nome        FELIPE
ID_aluno       171
Name: 17, dtype: object
nome        RAIMUNDO
ID_aluno         169
Name: 18, dtype: object
nome        RODRIGO
ID_aluno        150
Name: 19, dtype: object
nome        MANOEL
ID_aluno       225
Name: 20, dtype: object
nome        MATEUS
ID_aluno        92
Name: 21, dtype: object
nome        ANDRE
ID_aluno      212
Name: 22, dtype: object
nome        FERNANDO
ID_aluno         219
Name: 23, dtype: object
nome        FABIO
ID_aluno      109
Name: 24, dtype: object
nome        LEONARDO
ID_aluno         381
Name: 25, dtype: object
nome        GUSTAVO
ID_aluno        173
Name: 26, dtype: object
nome        GUILHERME
ID_aluno          186
Name: 27, dtype: object
nome        LEANDRO
ID_aluno        139
Name: 28, dtype: object
nome        TIAGO
ID_aluno      315
Name: 29, dtype: object
nome        ANDERSON
ID_aluno         264
Name: 30, dtype: object
nome        RICARDO
ID_aluno        358
Name: 31, dtype: object
nome        MARCIO
ID_aluno       286
Name: 32, dtype: object
nome        JORGE
ID_aluno      129
Name: 33, dtype: object
nome        SEBASTIAO
ID_aluno           76
Name: 34, dtype: object
nome        ALEXANDRE
ID_aluno          126
Name: 35, dtype: object
nome        ROBERTO
ID_aluno         53
Name: 36, dtype: object
nome        EDSON
ID_aluno       93
Name: 37, dtype: object
nome        DIEGO
ID_aluno      297
Name: 38, dtype: object
nome        VITOR
ID_aluno       79
Name: 39, dtype: object
nome        SERGIO
ID_aluno        37
Name: 40, dtype: object
nome        CLAUDIO
ID_aluno        227
Name: 41, dtype: object
nome        MATHEUS
ID_aluno        228
Name: 42, dtype: object
nome        THIAGO
ID_aluno        49
Name: 43, dtype: object
nome        GERALDO
ID_aluno        280
Name: 44, dtype: object
nome        ADRIANO
ID_aluno         91
Name: 45, dtype: object
nome        LUCIANO
ID_aluno        373
Name: 46, dtype: object
nome        JULIO
ID_aluno       56
Name: 47, dtype: object
nome        RENATO
ID_aluno       223
Name: 48, dtype: object
nome        ALEX
ID_aluno     222
Name: 49, dtype: object
nome        VINICIUS
ID_aluno         303
Name: 50, dtype: object
nome        ROGERIO
ID_aluno        343
Name: 51, dtype: object
nome        SAMUEL
ID_aluno       375
Name: 52, dtype: object
nome        RONALDO
ID_aluno         66
Name: 53, dtype: object
nome        MARIO
ID_aluno      145
Name: 54, dtype: object
nome        FLAVIO
ID_aluno       305
Name: 55, dtype: object
nome        DOUGLAS
ID_aluno        266
Name: 56, dtype: object
nome        IGOR
ID_aluno     178
Name: 57, dtype: object
nome        DAVI
ID_aluno     174
Name: 58, dtype: object
nome        MANUEL
ID_aluno       261
Name: 59, dtype: object
nome        JEFERSON
ID_aluno         366
Name: 60, dtype: object
nome        CICERO
ID_aluno       107
Name: 61, dtype: object
nome        VICTOR
ID_aluno       187
Name: 62, dtype: object
nome        MIGUEL
ID_aluno       278
Name: 63, dtype: object
nome        ROBSON
ID_aluno        63
Name: 64, dtype: object
nome        MAURICIO
ID_aluno         349
Name: 65, dtype: object
nome        DANILO
ID_aluno         6
Name: 66, dtype: object
nome        HENRIQUE
ID_aluno         272
Name: 67, dtype: object
nome        CAIO
ID_aluno     210
Name: 68, dtype: object
nome        REGINALDO
ID_aluno          207
Name: 69, dtype: object
nome        JOAQUIM
ID_aluno        194
Name: 70, dtype: object
nome        BENEDITO
ID_aluno         326
Name: 71, dtype: object
nome        GILBERTO
ID_aluno          17
Name: 72, dtype: object
nome        MARCO
ID_aluno      230
Name: 73, dtype: object
nome        ALAN
ID_aluno      36
Name: 74, dtype: object
nome        NELSON
ID_aluno       136
Name: 75, dtype: object
nome        CRISTIANO
ID_aluno          369
Name: 76, dtype: object
nome        ELIAS
ID_aluno       42
Name: 77, dtype: object
nome        WILSON
ID_aluno        57
Name: 78, dtype: object
nome        VALDIR
ID_aluno       131
Name: 79, dtype: object
nome        EMERSON
ID_aluno        163
Name: 80, dtype: object
nome        LUAN
ID_aluno     101
Name: 81, dtype: object
nome        DAVID
ID_aluno      118
Name: 82, dtype: object
nome        RENAN
ID_aluno      140
Name: 83, dtype: object
nome        SEVERINO
ID_aluno         216
Name: 84, dtype: object
nome        FABRICIO
ID_aluno         220
Name: 85, dtype: object
nome        MAURO
ID_aluno      338
Name: 86, dtype: object
nome        JONAS
ID_aluno      274
Name: 87, dtype: object
nome        GILMAR
ID_aluno       165
Name: 88, dtype: object
nome        JEAN
ID_aluno      75
Name: 89, dtype: object
nome        FABIANO
ID_aluno        195
Name: 90, dtype: object
nome        WESLEY
ID_aluno       238
Name: 91, dtype: object
nome        DIOGO
ID_aluno      346
Name: 92, dtype: object
nome        ADILSON
ID_aluno        301
Name: 93, dtype: object
nome        JAIR
ID_aluno     217
Name: 94, dtype: object
nome        ALESSANDRO
ID_aluno           190
Name: 95, dtype: object
nome        EVERTON
ID_aluno        233
Name: 96, dtype: object
nome        OSVALDO
ID_aluno         71
Name: 97, dtype: object
nome        GILSON
ID_aluno        12
Name: 98, dtype: object
nome        WILLIAN
ID_aluno        253
Name: 99, dtype: object
nome        JOEL
ID_aluno     361
Name: 100, dtype: object
nome        SILVIO
ID_aluno       282
Name: 101, dtype: object
nome        HELIO
ID_aluno       68
Name: 102, dtype: object
nome        MAICON
ID_aluno       148
Name: 103, dtype: object
nome        REINALDO
ID_aluno         314
Name: 104, dtype: object
nome        PABLO
ID_aluno      245
Name: 105, dtype: object
nome        ARTUR
ID_aluno       96
Name: 106, dtype: object
nome        VAGNER
ID_aluno       324
Name: 107, dtype: object
nome        VALTER
ID_aluno       300
Name: 108, dtype: object
nome        CELSO
ID_aluno      221
Name: 109, dtype: object
nome        IVAN
ID_aluno     400
Name: 110, dtype: object
nome        CLEITON
ID_aluno        155
Name: 111, dtype: object
nome        VANDERLEI
ID_aluno          135
Name: 112, dtype: object
nome        VICENTE
ID_aluno        347
Name: 113, dtype: object
nome        ARTHUR
ID_aluno       201
Name: 114, dtype: object
nome        MILTON
ID_aluno       255
Name: 115, dtype: object
nome        DOMINGOS
ID_aluno          14
Name: 116, dtype: object
nome        WAGNER
ID_aluno       329
Name: 117, dtype: object
nome        SANDRO
ID_aluno       211
Name: 118, dtype: object
nome        MOISES
ID_aluno       146
Name: 119, dtype: object
nome        EDILSON
ID_aluno        179
Name: 120, dtype: object
nome        ADEMIR
ID_aluno       203
Name: 121, dtype: object
nome        ADAO
ID_aluno     273
Name: 122, dtype: object
nome        EVANDRO
ID_aluno         84
Name: 123, dtype: object
nome        CESAR
ID_aluno       55
Name: 124, dtype: object
nome        VALMIR
ID_aluno       276
Name: 125, dtype: object
nome        MURILO
ID_aluno       355
Name: 126, dtype: object
nome        JULIANO
ID_aluno        304
Name: 127, dtype: object
nome        EDVALDO
ID_aluno        362
Name: 128, dtype: object
nome        AILTON
ID_aluno        98
Name: 129, dtype: object
nome        JUNIOR
ID_aluno        18
Name: 130, dtype: object
nome        BRENO
ID_aluno       44
Name: 131, dtype: object
nome        NICOLAS
ID_aluno         26
Name: 132, dtype: object
nome        RUAN
ID_aluno     147
Name: 133, dtype: object
nome        ALBERTO
ID_aluno          2
Name: 134, dtype: object
nome        RUBENS
ID_aluno       205
Name: 135, dtype: object
nome        NILTON
ID_aluno       256
Name: 136, dtype: object
nome        AUGUSTO
ID_aluno         87
Name: 137, dtype: object
nome        CLEBER
ID_aluno       103
Name: 138, dtype: object
nome        OSMAR
ID_aluno      197
Name: 139, dtype: object
nome        NILSON
ID_aluno       317
Name: 140, dtype: object
nome        ORLANDO
ID_aluno        177
Name: 141, dtype: object
nome        HUGO
ID_aluno     108
Name: 142, dtype: object
nome        OTAVIO
ID_aluno       241
Name: 143, dtype: object
nome        VINICIOS
ID_aluno         311
Name: 144, dtype: object
nome        ITALO
ID_aluno       40
Name: 145, dtype: object
nome        WILIAN
ID_aluno        97
Name: 146, dtype: object
nome        ALISSON
ID_aluno         15
Name: 147, dtype: object
nome        APARECIDO
ID_aluno          334
Name: 148, dtype: object
nome        ISRAEL
ID_aluno        89
Name: 149, dtype: object
nome        EDMILSON
ID_aluno         399
Name: 150, dtype: object
nome        JOSUE
ID_aluno      316
Name: 151, dtype: object
nome        GERSON
ID_aluno       157
Name: 152, dtype: object
nome        CAUA
ID_aluno     130
Name: 153, dtype: object
nome        SIDNEI
ID_aluno         4
Name: 154, dtype: object
nome        EMANUEL
ID_aluno        110
Name: 155, dtype: object
nome        VALDEMAR
ID_aluno         295
Name: 156, dtype: object
nome        JAIME
ID_aluno       78
Name: 157, dtype: object
nome        EDIVALDO
ID_aluno         287
Name: 158, dtype: object
nome        ARNALDO
ID_aluno         29
Name: 159, dtype: object
nome        MOACIR
ID_aluno       390
Name: 160, dtype: object
nome        DAMIAO
ID_aluno        99
Name: 161, dtype: object
nome        ISMAEL
ID_aluno       185
Name: 162, dtype: object
nome        NIVALDO
ID_aluno        340
Name: 163, dtype: object
nome        JAIRO
ID_aluno       80
Name: 164, dtype: object
nome        ISAIAS
ID_aluno       313
Name: 165, dtype: object
nome        MICHEL
ID_aluno        45
Name: 166, dtype: object
nome        ANGELO
ID_aluno       330
Name: 167, dtype: object
nome        CRISTIAN
ID_aluno          51
Name: 168, dtype: object
nome        WELLINGTON
ID_aluno           167
Name: 169, dtype: object
nome        ALEXANDRO
ID_aluno            8
Name: 170, dtype: object
nome        VALDEMIR
ID_aluno         236
Name: 171, dtype: object
nome        WANDERSON
ID_aluno          281
Name: 172, dtype: object
nome        JAILSON
ID_aluno        341
Name: 173, dtype: object
nome        DENIS
ID_aluno      151
Name: 174, dtype: object
nome        RIAN
ID_aluno     198
Name: 175, dtype: object
nome        CELIO
ID_aluno      320
Name: 176, dtype: object
nome        CLAUDINEI
ID_aluno           86
Name: 177, dtype: object
nome        DENILSON
ID_aluno         385
Name: 178, dtype: object
nome        IAGO
ID_aluno     133
Name: 179, dtype: object
nome        EDER
ID_aluno      88
Name: 180, dtype: object
nome        YURI
ID_aluno      10
Name: 181, dtype: object
nome        CHARLES
ID_aluno         47
Name: 182, dtype: object
nome        MARLON
ID_aluno       251
Name: 183, dtype: object
nome        ALISON
ID_aluno       252
Name: 184, dtype: object
nome        JONATAN
ID_aluno         38
Name: 185, dtype: object
nome        ERIC
ID_aluno      83
Name: 186, dtype: object
nome        ELTON
ID_aluno       65
Name: 187, dtype: object
nome        VALDECIR
ID_aluno         166
Name: 188, dtype: object
nome        WESLEI
ID_aluno       240
Name: 189, dtype: object
nome        NATANAEL
ID_aluno         242
Name: 190, dtype: object
nome        ERICK
ID_aluno        3
Name: 191, dtype: object
nome        AGNALDO
ID_aluno        113
Name: 192, dtype: object
nome        KAUAN
ID_aluno      120
Name: 193, dtype: object
nome        ODAIR
ID_aluno      306
Name: 194, dtype: object
nome        WALTER
ID_aluno       354
Name: 195, dtype: object
nome        ARLINDO
ID_aluno        224
Name: 196, dtype: object
nome        MICHAEL
ID_aluno        357
Name: 197, dtype: object
nome        ALVARO
ID_aluno       247
Name: 198, dtype: object
nome        GEOVANE
ID_aluno        339
Name: 199, dtype: object
nome        MARIA
ID_aluno      275
Name: 200, dtype: object
nome        ANA
ID_aluno    394
Name: 201, dtype: object
nome        FRANCISCA
ID_aluno          122
Name: 202, dtype: object
nome        ANTONIA
ID_aluno        360
Name: 203, dtype: object
nome        ADRIANA
ID_aluno        162
Name: 204, dtype: object
nome        JULIANA
ID_aluno        363
Name: 205, dtype: object
nome        MARCIA
ID_aluno       168
Name: 206, dtype: object
nome        FERNANDA
ID_aluno         258
Name: 207, dtype: object
nome        PATRICIA
ID_aluno         294
Name: 208, dtype: object
nome        ALINE
ID_aluno      323
Name: 209, dtype: object
nome        SANDRA
ID_aluno       152
Name: 210, dtype: object
nome        CAMILA
ID_aluno       183
Name: 211, dtype: object
nome        AMANDA
ID_aluno        77
Name: 212, dtype: object
nome        BRUNA
ID_aluno       60
Name: 213, dtype: object
nome        JESSICA
ID_aluno        271
Name: 214, dtype: object
nome        LETICIA
ID_aluno        196
Name: 215, dtype: object
nome        JULIA
ID_aluno       41
Name: 216, dtype: object
nome        LUCIANA
ID_aluno        100
Name: 217, dtype: object
nome        VANESSA
ID_aluno        267
Name: 218, dtype: object
nome        MARIANA
ID_aluno        388
Name: 219, dtype: object
nome        GABRIELA
ID_aluno         218
Name: 220, dtype: object
nome        VERA
ID_aluno      52
Name: 221, dtype: object
nome        VITORIA
ID_aluno        364
Name: 222, dtype: object
nome        LARISSA
ID_aluno        134
Name: 223, dtype: object
nome        CLAUDIA
ID_aluno        199
Name: 224, dtype: object
nome        BEATRIZ
ID_aluno        158
Name: 225, dtype: object
nome        RITA
ID_aluno     395
Name: 226, dtype: object
nome        LUANA
ID_aluno      125
Name: 227, dtype: object
nome        SONIA
ID_aluno      336
Name: 228, dtype: object
nome        RENATA
ID_aluno        69
Name: 229, dtype: object
nome        ELIANE
ID_aluno        74
Name: 230, dtype: object
nome        JOSEFA
ID_aluno       307
Name: 231, dtype: object
nome        SIMONE
ID_aluno       344
Name: 232, dtype: object
nome        NATALIA
ID_aluno        170
Name: 233, dtype: object
nome        CRISTIANE
ID_aluno          270
Name: 234, dtype: object
nome        CARLA
ID_aluno      365
Name: 235, dtype: object
nome        DEBORA
ID_aluno        35
Name: 236, dtype: object
nome        ROSANGELA
ID_aluno          248
Name: 237, dtype: object
nome        JAQUELINE
ID_aluno           54
Name: 238, dtype: object
nome        ROSA
ID_aluno     284
Name: 239, dtype: object
nome        APARECIDA
ID_aluno          159
Name: 240, dtype: object
nome        DANIELA
ID_aluno        164
Name: 241, dtype: object
nome        MARLENE
ID_aluno        392
Name: 242, dtype: object
nome        TEREZINHA
ID_aluno          160
Name: 243, dtype: object
nome        RAIMUNDA
ID_aluno          32
Name: 244, dtype: object
nome        ANDREIA
ID_aluno        184
Name: 245, dtype: object
nome        FABIANA
ID_aluno        111
Name: 246, dtype: object
nome        LUCIA
ID_aluno       21
Name: 247, dtype: object
nome        RAQUEL
ID_aluno        22
Name: 248, dtype: object
nome        ANGELA
ID_aluno       308
Name: 249, dtype: object
nome        RAFAELA
ID_aluno        328
Name: 250, dtype: object
nome        JOANA
ID_aluno       28
Name: 251, dtype: object
nome        LUZIA
ID_aluno      104
Name: 252, dtype: object
nome        ELAINE
ID_aluno       374
Name: 253, dtype: object
nome        REGINA
ID_aluno       138
Name: 254, dtype: object
nome        DANIELE
ID_aluno        350
Name: 255, dtype: object
nome        SUELI
ID_aluno      161
Name: 256, dtype: object
nome        DAIANE
ID_aluno       288
Name: 257, dtype: object
nome        ALESSANDRA
ID_aluno           121
Name: 258, dtype: object
nome        ISABEL
ID_aluno       262
Name: 259, dtype: object
nome        SARA
ID_aluno     128
Name: 260, dtype: object
nome        BIANCA
ID_aluno       335
Name: 261, dtype: object
nome        FLAVIA
ID_aluno        70
Name: 262, dtype: object
nome        ERICA
ID_aluno       81
Name: 263, dtype: object
nome        VIVIANE
ID_aluno        188
Name: 264, dtype: object
nome        SILVANA
ID_aluno        356
Name: 265, dtype: object
nome        PRISCILA
ID_aluno         299
Name: 266, dtype: object
nome        PAULA
ID_aluno      386
Name: 267, dtype: object
nome        LUIZA
ID_aluno      193
Name: 268, dtype: object
nome        TEREZA
ID_aluno        23
Name: 269, dtype: object
nome        ISABELA
ID_aluno        182
Name: 270, dtype: object
nome        MARTA
ID_aluno      292
Name: 271, dtype: object
nome        CAROLINE
ID_aluno         176
Name: 272, dtype: object
nome        JANAINA
ID_aluno        137
Name: 273, dtype: object
nome        LAURA
ID_aluno      123
Name: 274, dtype: object
nome        MARLI
ID_aluno       48
Name: 275, dtype: object
nome        TATIANE
ID_aluno        332
Name: 276, dtype: object
nome        MARINA
ID_aluno       213
Name: 277, dtype: object
nome        SILVIA
ID_aluno        67
Name: 278, dtype: object
nome        MONICA
ID_aluno       191
Name: 279, dtype: object
nome        TAIS
ID_aluno      85
Name: 280, dtype: object
nome        MICHELE
ID_aluno        243
Name: 281, dtype: object
nome        SOLANGE
ID_aluno        156
Name: 282, dtype: object
nome        EDNA
ID_aluno     263
Name: 283, dtype: object
nome        FATIMA
ID_aluno       142
Name: 284, dtype: object
nome        HELENA
ID_aluno       352
Name: 285, dtype: object
nome        CRISTINA
ID_aluno         102
Name: 286, dtype: object
nome        ALICE
ID_aluno      229
Name: 287, dtype: object
nome        CAROLINA
ID_aluno         384
Name: 288, dtype: object
nome        ROSANA
ID_aluno       342
Name: 289, dtype: object
nome        ANDRESSA
ID_aluno         359
Name: 290, dtype: object
nome        CELIA
ID_aluno      215
Name: 291, dtype: object
nome        VALERIA
ID_aluno        345
Name: 292, dtype: object
nome        ELIANA
ID_aluno        95
Name: 293, dtype: object
nome        SABRINA
ID_aluno        289
Name: 294, dtype: object
nome        ANDREA
ID_aluno       279
Name: 295, dtype: object
nome        TANIA
ID_aluno      257
Name: 296, dtype: object
nome        BARBARA
ID_aluno        246
Name: 297, dtype: object

nome        THAIS
ID_aluno      337
Name: 298, dtype: object
nome        DENISE
ID_aluno       396
Name: 299, dtype: object
nome        ROSELI
ID_aluno       302
Name: 300, dtype: object
nome        GISELE
ID_aluno       214
Name: 301, dtype: object
nome        MARILENE
ID_aluno         290
Name: 302, dtype: object
nome        KATIA
ID_aluno      143
Name: 303, dtype: object
nome        EVA
ID_aluno    351
Name: 304, dtype: object
nome        MILENA
ID_aluno       318
Name: 305, dtype: object
nome        EDUARDA
ID_aluno        293
Name: 306, dtype: object
nome        ELISANGELA
ID_aluno            46
Name: 307, dtype: object
nome        VILMA
ID_aluno      371
Name: 308, dtype: object
nome        GEOVANA
ID_aluno        325
Name: 309, dtype: object
nome        LUCIENE
ID_aluno        144
Name: 310, dtype: object
nome        TAMIRES
ID_aluno        319
Name: 311, dtype: object
nome        TATIANA
ID_aluno        298
Name: 312, dtype: object
nome        ROBERTA
ID_aluno         27
Name: 313, dtype: object
nome        ELZA
ID_aluno     269
Name: 314, dtype: object
nome        TALITA
ID_aluno        64
Name: 315, dtype: object
nome        MARCELA
ID_aluno        291
Name: 316, dtype: object
nome        PAMELA
ID_aluno       232
Name: 317, dtype: object
nome        VANIA
ID_aluno      254
Name: 318, dtype: object
nome        IRENE
ID_aluno       34
Name: 319, dtype: object
nome        JOSIANE
ID_aluno        398
Name: 320, dtype: object
nome        LIVIA
ID_aluno      370
Name: 321, dtype: object
nome        CINTIA
ID_aluno       119
Name: 322, dtype: object
nome        IVONE
ID_aluno       16
Name: 323, dtype: object
nome        LAIS
ID_aluno     393
Name: 324, dtype: object
nome        BENEDITA
ID_aluno          43
Name: 325, dtype: object
nome        SEBASTIANA
ID_aluno           192
Name: 326, dtype: object
nome        TAINA
ID_aluno      175
Name: 327, dtype: object
nome        JOICE
ID_aluno      333
Name: 328, dtype: object
nome        MIRIAN
ID_aluno       249
Name: 329, dtype: object
nome        ELIZABETE
ID_aluno           11
Name: 330, dtype: object
nome        ANGELICA
ID_aluno          94
Name: 331, dtype: object
nome        GABRIELE
ID_aluno         389
Name: 332, dtype: object
nome        BRENDA
ID_aluno       367
Name: 333, dtype: object
nome        VERONICA
ID_aluno           7
Name: 334, dtype: object
nome        ROSILENE
ID_aluno         376
Name: 335, dtype: object
nome        KARINA
ID_aluno       154
Name: 336, dtype: object
nome        NAIR
ID_aluno     117
Name: 337, dtype: object
nome        NEUSA
ID_aluno       20
Name: 338, dtype: object
nome        MARGARIDA
ID_aluno          124
Name: 339, dtype: object
nome        NEUZA
ID_aluno      353
Name: 340, dtype: object
nome        NEIDE
ID_aluno       61
Name: 341, dtype: object
nome        RAISSA
ID_aluno        19
Name: 342, dtype: object
nome        MAIARA
ID_aluno        24
Name: 343, dtype: object
nome        LORENA
ID_aluno       277
Name: 344, dtype: object
nome        FRANCIELE
ID_aluno           31
Name: 345, dtype: object
nome        SAMARA
ID_aluno       226
Name: 346, dtype: object
nome        LILIAN
ID_aluno         1
Name: 347, dtype: object
nome        JANETE
ID_aluno        73
Name: 348, dtype: object
nome        CICERA
ID_aluno       114
Name: 349, dtype: object
nome        GIOVANA
ID_aluno        202
Name: 350, dtype: object
nome        SEVERINA
ID_aluno         368
Name: 351, dtype: object
nome        LARA
ID_aluno     112
Name: 352, dtype: object
nome        CLEIDE
ID_aluno       116
Name: 353, dtype: object
nome        NICOLE
ID_aluno       310
Name: 354, dtype: object
nome        CECILIA
ID_aluno         33
Name: 355, dtype: object
nome        YASMIN
ID_aluno       153
Name: 356, dtype: object
nome        CONCEICAO
ID_aluno          331
Name: 357, dtype: object
nome        INGRID
ID_aluno       397
Name: 358, dtype: object
nome        SELMA
ID_aluno       39
Name: 359, dtype: object
nome        LEILA
ID_aluno       25
Name: 360, dtype: object
nome        RAIANE
ID_aluno        30
Name: 361, dtype: object
nome        ESTER
ID_aluno      327
Name: 362, dtype: object
nome        REGIANE
ID_aluno        200
Name: 363, dtype: object
nome        MARISA
ID_aluno       206
Name: 364, dtype: object
nome        EUNICE
ID_aluno       321
Name: 365, dtype: object
nome        KELLY
ID_aluno      372
Name: 366, dtype: object
nome        TAINARA
ID_aluno        180
Name: 367, dtype: object
nome        IARA
ID_aluno     377
Name: 368, dtype: object
nome        JOELMA
ID_aluno       260
Name: 369, dtype: object
nome        MARINALVA
ID_aluno          181
Name: 370, dtype: object
nome        TERESINHA
ID_aluno          312
Name: 371, dtype: object
nome        REBECA
ID_aluno       259
Name: 372, dtype: object
nome        GERALDA
ID_aluno        209
Name: 373, dtype: object
nome        CLEONICE
ID_aluno         265
Name: 374, dtype: object
nome        ALEXANDRA
ID_aluno          127
Name: 375, dtype: object
nome        MARA
ID_aluno     382
Name: 376, dtype: object
nome        JENIFER
ID_aluno        208
Name: 377, dtype: object
nome        ELIZANGELA
ID_aluno           309
Name: 378, dtype: object
nome        LILIANE
ID_aluno        296
Name: 379, dtype: object
nome        LIDIA
ID_aluno       62
Name: 380, dtype: object
nome        IRACEMA
ID_aluno        380
Name: 381, dtype: object
nome        LIDIANE
ID_aluno        239
Name: 382, dtype: object
nome        IRACI
ID_aluno      283
Name: 383, dtype: object
nome        MARILIA
ID_aluno        141
Name: 384, dtype: object
nome        SHEILA
ID_aluno       149
Name: 385, dtype: object
nome        INES
ID_aluno     379
Name: 386, dtype: object
nome        NAIARA
ID_aluno        82
Name: 387, dtype: object
nome        POLIANA
ID_aluno        391
Name: 388, dtype: object
nome        DALVA
ID_aluno      106
Name: 389, dtype: object
nome        LURDES
ID_aluno        72
Name: 390, dtype: object
nome        TERESA
ID_aluno       115
Name: 391, dtype: object
nome        ZILDA
ID_aluno      235
Name: 392, dtype: object
nome        LUCILENE
ID_aluno         348
Name: 393, dtype: object
nome        CLARA
ID_aluno      234
Name: 394, dtype: object
nome        ROSANE
ID_aluno         9
Name: 395, dtype: object
nome        IVONETE
ID_aluno        378
Name: 396, dtype: object
nome        LUCIANE
ID_aluno         50
Name: 397, dtype: object
nome        ISADORA
ID_aluno        244
Name: 398, dtype: object
nome        NILZA
ID_aluno      387
Name: 399, dtype: object

In [41]:
#Retornando dados de mais de uma coluna especificada
for i, id_aluno in df[['nome', 'ID_aluno']].iterrows():
    print(f"Nome: {id_aluno['nome']} -> Id_aluno: {id_aluno['ID_aluno']}")

Nome: JOSE -> Id_aluno: 189
Nome: JOAO -> Id_aluno: 58
Nome: ANTONIO -> Id_aluno: 204
Nome: FRANCISCO -> Id_aluno: 383
Nome: CARLOS -> Id_aluno: 231
Nome: PAULO -> Id_aluno: 285
Nome: PEDRO -> Id_aluno: 105
Nome: LUCAS -> Id_aluno: 237
Nome: LUIZ -> Id_aluno: 5
Nome: MARCOS -> Id_aluno: 268
Nome: LUIS -> Id_aluno: 59
Nome: GABRIEL -> Id_aluno: 132
Nome: RAFAEL -> Id_aluno: 13
Nome: DANIEL -> Id_aluno: 172
Nome: MARCELO -> Id_aluno: 322
Nome: BRUNO -> Id_aluno: 90
Nome: EDUARDO -> Id_aluno: 250
Nome: FELIPE -> Id_aluno: 171
Nome: RAIMUNDO -> Id_aluno: 169
Nome: RODRIGO -> Id_aluno: 150
Nome: MANOEL -> Id_aluno: 225
Nome: MATEUS -> Id_aluno: 92
Nome: ANDRE -> Id_aluno: 212
Nome: FERNANDO -> Id_aluno: 219
Nome: FABIO -> Id_aluno: 109
Nome: LEONARDO -> Id_aluno: 381
Nome: GUSTAVO -> Id_aluno: 173
Nome: GUILHERME -> Id_aluno: 186
Nome: LEANDRO -> Id_aluno: 139
Nome: TIAGO -> Id_aluno: 315
Nome: ANDERSON -> Id_aluno: 264
Nome: RICARDO -> Id_aluno: 358
Nome: MARCIO -> Id_aluno: 286
Nome: JORGE -> Id_aluno: 129
Nome: SEBASTIAO -> Id_aluno: 76
Nome: ALEXANDRE -> Id_aluno: 126
Nome: ROBERTO -> Id_aluno: 53
Nome: EDSON -> Id_aluno: 93
Nome: DIEGO -> Id_aluno: 297
Nome: VITOR -> Id_aluno: 79
Nome: SERGIO -> Id_aluno: 37
Nome: CLAUDIO -> Id_aluno: 227
Nome: MATHEUS -> Id_aluno: 228
Nome: THIAGO -> Id_aluno: 49
Nome: GERALDO -> Id_aluno: 280
Nome: ADRIANO -> Id_aluno: 91
Nome: LUCIANO -> Id_aluno: 373
Nome: JULIO -> Id_aluno: 56
Nome: RENATO -> Id_aluno: 223
Nome: ALEX -> Id_aluno: 222
Nome: VINICIUS -> Id_aluno: 303
Nome: ROGERIO -> Id_aluno: 343
Nome: SAMUEL -> Id_aluno: 375
Nome: RONALDO -> Id_aluno: 66
Nome: MARIO -> Id_aluno: 145
Nome: FLAVIO -> Id_aluno: 305
Nome: DOUGLAS -> Id_aluno: 266
Nome: IGOR -> Id_aluno: 178
Nome: DAVI -> Id_aluno: 174
Nome: MANUEL -> Id_aluno: 261
Nome: JEFERSON -> Id_aluno: 366
Nome: CICERO -> Id_aluno: 107
Nome: VICTOR -> Id_aluno: 187
Nome: MIGUEL -> Id_aluno: 278
Nome: ROBSON -> Id_aluno: 63
Nome: MAURICIO -> Id_aluno: 349
Nome: DANILO -> Id_aluno: 6
Nome: HENRIQUE -> Id_aluno: 272
Nome: CAIO -> Id_aluno: 210
Nome: REGINALDO -> Id_aluno: 207
Nome: JOAQUIM -> Id_aluno: 194
Nome: BENEDITO -> Id_aluno: 326
Nome: GILBERTO -> Id_aluno: 17
Nome: MARCO -> Id_aluno: 230
Nome: ALAN -> Id_aluno: 36
Nome: NELSON -> Id_aluno: 136
Nome: CRISTIANO -> Id_aluno: 369
Nome: ELIAS -> Id_aluno: 42
Nome: WILSON -> Id_aluno: 57
Nome: VALDIR -> Id_aluno: 131
Nome: EMERSON -> Id_aluno: 163
Nome: LUAN -> Id_aluno: 101
Nome: DAVID -> Id_aluno: 118
Nome: RENAN -> Id_aluno: 140
Nome: SEVERINO -> Id_aluno: 216
Nome: FABRICIO -> Id_aluno: 220
Nome: MAURO -> Id_aluno: 338
Nome: JONAS -> Id_aluno: 274
Nome: GILMAR -> Id_aluno: 165
Nome: JEAN -> Id_aluno: 75
Nome: FABIANO -> Id_aluno: 195
Nome: WESLEY -> Id_aluno: 238
Nome: DIOGO -> Id_aluno: 346
Nome: ADILSON -> Id_aluno: 301
Nome: JAIR -> Id_aluno: 217
Nome: ALESSANDRO -> Id_aluno: 190
Nome: EVERTON -> Id_aluno: 233
Nome: OSVALDO -> Id_aluno: 71
Nome: GILSON -> Id_aluno: 12
Nome: WILLIAN -> Id_aluno: 253
Nome: JOEL -> Id_aluno: 361
Nome: SILVIO -> Id_aluno: 282
Nome: HELIO -> Id_aluno: 68
Nome: MAICON -> Id_aluno: 148
Nome: REINALDO -> Id_aluno: 314
Nome: PABLO -> Id_aluno: 245
Nome: ARTUR -> Id_aluno: 96
Nome: VAGNER -> Id_aluno: 324
Nome: VALTER -> Id_aluno: 300
Nome: CELSO -> Id_aluno: 221
Nome: IVAN -> Id_aluno: 400
Nome: CLEITON -> Id_aluno: 155
Nome: VANDERLEI -> Id_aluno: 135
Nome: VICENTE -> Id_aluno: 347
Nome: ARTHUR -> Id_aluno: 201
Nome: MILTON -> Id_aluno: 255
Nome: DOMINGOS -> Id_aluno: 14
Nome: WAGNER -> Id_aluno: 329
Nome: SANDRO -> Id_aluno: 211
Nome: MOISES -> Id_aluno: 146
Nome: EDILSON -> Id_aluno: 179
Nome: ADEMIR -> Id_aluno: 203
Nome: ADAO -> Id_aluno: 273
Nome: EVANDRO -> Id_aluno: 84
Nome: CESAR -> Id_aluno: 55
Nome: VALMIR -> Id_aluno: 276
Nome: MURILO -> Id_aluno: 355
Nome: JULIANO -> Id_aluno: 304
Nome: EDVALDO -> Id_aluno: 362
Nome: AILTON -> Id_aluno: 98
Nome: JUNIOR -> Id_aluno: 18
Nome: BRENO -> Id_aluno: 44
Nome: NICOLAS -> Id_aluno: 26
Nome: RUAN -> Id_aluno: 147
Nome: ALBERTO -> Id_aluno: 2
Nome: RUBENS -> Id_aluno: 205
Nome: NILTON -> Id_aluno: 256
Nome: AUGUSTO -> Id_aluno: 87
Nome: CLEBER -> Id_aluno: 103
Nome: OSMAR -> Id_aluno: 197
Nome: NILSON -> Id_aluno: 317
Nome: ORLANDO -> Id_aluno: 177
Nome: HUGO -> Id_aluno: 108
Nome: OTAVIO -> Id_aluno: 241
Nome: VINICIOS -> Id_aluno: 311
Nome: ITALO -> Id_aluno: 40
Nome: WILIAN -> Id_aluno: 97
Nome: ALISSON -> Id_aluno: 15
Nome: APARECIDO -> Id_aluno: 334
Nome: ISRAEL -> Id_aluno: 89
Nome: EDMILSON -> Id_aluno: 399
Nome: JOSUE -> Id_aluno: 316
Nome: GERSON -> Id_aluno: 157
Nome: CAUA -> Id_aluno: 130
Nome: SIDNEI -> Id_aluno: 4
Nome: EMANUEL -> Id_aluno: 110
Nome: VALDEMAR -> Id_aluno: 295
Nome: JAIME -> Id_aluno: 78
Nome: EDIVALDO -> Id_aluno: 287
Nome: ARNALDO -> Id_aluno: 29
Nome: MOACIR -> Id_aluno: 390
Nome: DAMIAO -> Id_aluno: 99
Nome: ISMAEL -> Id_aluno: 185
Nome: NIVALDO -> Id_aluno: 340
Nome: JAIRO -> Id_aluno: 80
Nome: ISAIAS -> Id_aluno: 313
Nome: MICHEL -> Id_aluno: 45
Nome: ANGELO -> Id_aluno: 330
Nome: CRISTIAN -> Id_aluno: 51
Nome: WELLINGTON -> Id_aluno: 167
Nome: ALEXANDRO -> Id_aluno: 8
Nome: VALDEMIR -> Id_aluno: 236
Nome: WANDERSON -> Id_aluno: 281
Nome: JAILSON -> Id_aluno: 341
Nome: DENIS -> Id_aluno: 151
Nome: RIAN -> Id_aluno: 198
Nome: CELIO -> Id_aluno: 320
Nome: CLAUDINEI -> Id_aluno: 86
Nome: DENILSON -> Id_aluno: 385
Nome: IAGO -> Id_aluno: 133
Nome: EDER -> Id_aluno: 88
Nome: YURI -> Id_aluno: 10
Nome: CHARLES -> Id_aluno: 47
Nome: MARLON -> Id_aluno: 251
Nome: ALISON -> Id_aluno: 252
Nome: JONATAN -> Id_aluno: 38
Nome: ERIC -> Id_aluno: 83
Nome: ELTON -> Id_aluno: 65
Nome: VALDECIR -> Id_aluno: 166
Nome: WESLEI -> Id_aluno: 240
Nome: NATANAEL -> Id_aluno: 242
Nome: ERICK -> Id_aluno: 3
Nome: AGNALDO -> Id_aluno: 113
Nome: KAUAN -> Id_aluno: 120
Nome: ODAIR -> Id_aluno: 306
Nome: WALTER -> Id_aluno: 354
Nome: ARLINDO -> Id_aluno: 224
Nome: MICHAEL -> Id_aluno: 357
Nome: ALVARO -> Id_aluno: 247
Nome: GEOVANE -> Id_aluno: 339
Nome: MARIA -> Id_aluno: 275
Nome: ANA -> Id_aluno: 394
Nome: FRANCISCA -> Id_aluno: 122
Nome: ANTONIA -> Id_aluno: 360
Nome: ADRIANA -> Id_aluno: 162
Nome: JULIANA -> Id_aluno: 363
Nome: MARCIA -> Id_aluno: 168
Nome: FERNANDA -> Id_aluno: 258
Nome: PATRICIA -> Id_aluno: 294
Nome: ALINE -> Id_aluno: 323
Nome: SANDRA -> Id_aluno: 152
Nome: CAMILA -> Id_aluno: 183
Nome: AMANDA -> Id_aluno: 77
Nome: BRUNA -> Id_aluno: 60
Nome: JESSICA -> Id_aluno: 271
Nome: LETICIA -> Id_aluno: 196
Nome: JULIA -> Id_aluno: 41
Nome: LUCIANA -> Id_aluno: 100
Nome: VANESSA -> Id_aluno: 267
Nome: MARIANA -> Id_aluno: 388
Nome: GABRIELA -> Id_aluno: 218
Nome: VERA -> Id_aluno: 52
Nome: VITORIA -> Id_aluno: 364
Nome: LARISSA -> Id_aluno: 134
Nome: CLAUDIA -> Id_aluno: 199
Nome: BEATRIZ -> Id_aluno: 158
Nome: RITA -> Id_aluno: 395
Nome: LUANA -> Id_aluno: 125
Nome: SONIA -> Id_aluno: 336
Nome: RENATA -> Id_aluno: 69
Nome: ELIANE -> Id_aluno: 74
Nome: JOSEFA -> Id_aluno: 307
Nome: SIMONE -> Id_aluno: 344
Nome: NATALIA -> Id_aluno: 170
Nome: CRISTIANE -> Id_aluno: 270
Nome: CARLA -> Id_aluno: 365
Nome: DEBORA -> Id_aluno: 35
Nome: ROSANGELA -> Id_aluno: 248
Nome: JAQUELINE -> Id_aluno: 54
Nome: ROSA -> Id_aluno: 284
Nome: APARECIDA -> Id_aluno: 159
Nome: DANIELA -> Id_aluno: 164
Nome: MARLENE -> Id_aluno: 392
Nome: TEREZINHA -> Id_aluno: 160
Nome: RAIMUNDA -> Id_aluno: 32
Nome: ANDREIA -> Id_aluno: 184
Nome: FABIANA -> Id_aluno: 111
Nome: LUCIA -> Id_aluno: 21
Nome: RAQUEL -> Id_aluno: 22
Nome: ANGELA -> Id_aluno: 308
Nome: RAFAELA -> Id_aluno: 328
Nome: JOANA -> Id_aluno: 28
Nome: LUZIA -> Id_aluno: 104
Nome: ELAINE -> Id_aluno: 374
Nome: REGINA -> Id_aluno: 138
Nome: DANIELE -> Id_aluno: 350
Nome: SUELI -> Id_aluno: 161
Nome: DAIANE -> Id_aluno: 288
Nome: ALESSANDRA -> Id_aluno: 121
Nome: ISABEL -> Id_aluno: 262
Nome: SARA -> Id_aluno: 128
Nome: BIANCA -> Id_aluno: 335
Nome: FLAVIA -> Id_aluno: 70
Nome: ERICA -> Id_aluno: 81
Nome: VIVIANE -> Id_aluno: 188
Nome: SILVANA -> Id_aluno: 356
Nome: PRISCILA -> Id_aluno: 299
Nome: PAULA -> Id_aluno: 386
Nome: LUIZA -> Id_aluno: 193
Nome: TEREZA -> Id_aluno: 23
Nome: ISABELA -> Id_aluno: 182
Nome: MARTA -> Id_aluno: 292
Nome: CAROLINE -> Id_aluno: 176
Nome: JANAINA -> Id_aluno: 137
Nome: LAURA -> Id_aluno: 123
Nome: MARLI -> Id_aluno: 48
Nome: TATIANE -> Id_aluno: 332
Nome: MARINA -> Id_aluno: 213
Nome: SILVIA -> Id_aluno: 67
Nome: MONICA -> Id_aluno: 191
Nome: TAIS -> Id_aluno: 85
Nome: MICHELE -> Id_aluno: 243
Nome: SOLANGE -> Id_aluno: 156
Nome: EDNA -> Id_aluno: 263
Nome: FATIMA -> Id_aluno: 142
Nome: HELENA -> Id_aluno: 352
Nome: CRISTINA -> Id_aluno: 102
Nome: ALICE -> Id_aluno: 229
Nome: CAROLINA -> Id_aluno: 384
Nome: ROSANA -> Id_aluno: 342
Nome: ANDRESSA -> Id_aluno: 359
Nome: CELIA -> Id_aluno: 215
Nome: VALERIA -> Id_aluno: 345
Nome: ELIANA -> Id_aluno: 95
Nome: SABRINA -> Id_aluno: 289
Nome: ANDREA -> Id_aluno: 279
Nome: TANIA -> Id_aluno: 257
Nome: BARBARA -> Id_aluno: 246
Nome: THAIS -> Id_aluno: 337
Nome: DENISE -> Id_aluno: 396
Nome: ROSELI -> Id_aluno: 302
Nome: GISELE -> Id_aluno: 214
Nome: MARILENE -> Id_aluno: 290
Nome: KATIA -> Id_aluno: 143
Nome: EVA -> Id_aluno: 351
Nome: MILENA -> Id_aluno: 318
Nome: EDUARDA -> Id_aluno: 293
Nome: ELISANGELA -> Id_aluno: 46
Nome: VILMA -> Id_aluno: 371
Nome: GEOVANA -> Id_aluno: 325
Nome: LUCIENE -> Id_aluno: 144
Nome: TAMIRES -> Id_aluno: 319
Nome: TATIANA -> Id_aluno: 298
Nome: ROBERTA -> Id_aluno: 27
Nome: ELZA -> Id_aluno: 269
Nome: TALITA -> Id_aluno: 64
Nome: MARCELA -> Id_aluno: 291
Nome: PAMELA -> Id_aluno: 232
Nome: VANIA -> Id_aluno: 254
Nome: IRENE -> Id_aluno: 34
Nome: JOSIANE -> Id_aluno: 398
Nome: LIVIA -> Id_aluno: 370
Nome: CINTIA -> Id_aluno: 119
Nome: IVONE -> Id_aluno: 16
Nome: LAIS -> Id_aluno: 393
Nome: BENEDITA -> Id_aluno: 43
Nome: SEBASTIANA -> Id_aluno: 192
Nome: TAINA -> Id_aluno: 175
Nome: JOICE -> Id_aluno: 333
Nome: MIRIAN -> Id_aluno: 249
Nome: ELIZABETE -> Id_aluno: 11
Nome: ANGELICA -> Id_aluno: 94
Nome: GABRIELE -> Id_aluno: 389
Nome: BRENDA -> Id_aluno: 367
Nome: VERONICA -> Id_aluno: 7
Nome: ROSILENE -> Id_aluno: 376
Nome: KARINA -> Id_aluno: 154
Nome: NAIR -> Id_aluno: 117
Nome: NEUSA -> Id_aluno: 20
Nome: MARGARIDA -> Id_aluno: 124
Nome: NEUZA -> Id_aluno: 353
Nome: NEIDE -> Id_aluno: 61
Nome: RAISSA -> Id_aluno: 19
Nome: MAIARA -> Id_aluno: 24
Nome: LORENA -> Id_aluno: 277
Nome: FRANCIELE -> Id_aluno: 31
Nome: SAMARA -> Id_aluno: 226
Nome: LILIAN -> Id_aluno: 1
Nome: JANETE -> Id_aluno: 73
Nome: CICERA -> Id_aluno: 114
Nome: GIOVANA -> Id_aluno: 202
Nome: SEVERINA -> Id_aluno: 368
Nome: LARA -> Id_aluno: 112
Nome: CLEIDE -> Id_aluno: 116
Nome: NICOLE -> Id_aluno: 310
Nome: CECILIA -> Id_aluno: 33
Nome: YASMIN -> Id_aluno: 153
Nome: CONCEICAO -> Id_aluno: 331
Nome: INGRID -> Id_aluno: 397
Nome: SELMA -> Id_aluno: 39
Nome: LEILA -> Id_aluno: 25
Nome: RAIANE -> Id_aluno: 30
Nome: ESTER -> Id_aluno: 327
Nome: REGIANE -> Id_aluno: 200
Nome: MARISA -> Id_aluno: 206
Nome: EUNICE -> Id_aluno: 321
Nome: KELLY -> Id_aluno: 372
Nome: TAINARA -> Id_aluno: 180
Nome: IARA -> Id_aluno: 377
Nome: JOELMA -> Id_aluno: 260
Nome: MARINALVA -> Id_aluno: 181
Nome: TERESINHA -> Id_aluno: 312
Nome: REBECA -> Id_aluno: 259
Nome: GERALDA -> Id_aluno: 209
Nome: CLEONICE -> Id_aluno: 265
Nome: ALEXANDRA -> Id_aluno: 127
Nome: MARA -> Id_aluno: 382
Nome: JENIFER -> Id_aluno: 208
Nome: ELIZANGELA -> Id_aluno: 309
Nome: LILIANE -> Id_aluno: 296
Nome: LIDIA -> Id_aluno: 62
Nome: IRACEMA -> Id_aluno: 380
Nome: LIDIANE -> Id_aluno: 239
Nome: IRACI -> Id_aluno: 283
Nome: MARILIA -> Id_aluno: 141
Nome: SHEILA -> Id_aluno: 149
Nome: INES -> Id_aluno: 379
Nome: NAIARA -> Id_aluno: 82
Nome: POLIANA -> Id_aluno: 391
Nome: DALVA -> Id_aluno: 106
Nome: LURDES -> Id_aluno: 72
Nome: TERESA -> Id_aluno: 115
Nome: ZILDA -> Id_aluno: 235
Nome: LUCILENE -> Id_aluno: 348
Nome: CLARA -> Id_aluno: 234
Nome: ROSANE -> Id_aluno: 9
Nome: IVONETE -> Id_aluno: 378
Nome: LUCIANE -> Id_aluno: 50
Nome: ISADORA -> Id_aluno: 244
Nome: NILZA -> Id_aluno: 387